---
- name: Update all LXC containers
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get list of containers
      command: pct list
      register: pct_list

    - name: Extract container IDs
      set_fact:
        ct_ids: "{{ pct_list.stdout_lines[1:] | map('split') | map('first') | list }}"

    - name: Update each container
      command: /root/scripts/update.sh {{ item }}
      loop: "{{ ct_ids }}"
